### ISSUE TITLE
Unnecessary broad permissions for extension

### ISSUE THREAD

**Issue by sparr** [rafalimaz/TMTools#18]
When installing this extension, it asks for permission to access data on [all] websites, rather than specifically asking for permission for terra.snellman.net. I think this behavior might be triggered by https://github.com/rafalimaz/TMTools/blob/519789fcafb590660c719c318ad9ec2cb2360e38/manifest.json#L27

**Comment by rafalimaz** [comment]
Thank you very much.  I will check if the broad permissions are real necessary. In negative case, it will be removed.
